#[("USA", "TOP3000"), ("CHN", "TOP3000"), ("CHN", "TOP2000"), ("USA", "TOP1000"), ("USA", "TOP500"), ("USA", "TOP200")]
SELECT_REGION_UNIVERSE = [("USA", "TOP3000"),("USA", "TOP500")]
# [0, 1]
SELECT_DELAY = [1]
# ["NONE", "MARKET", "INDUSTRY", "SECTOR", "SUBINDUSTRY"]
SELECT_NEUTRALIZATION = ["NONE", "MARKET", "INDUSTRY", "SECTOR", "SUBINDUSTRY"]
# need to be int
SELECT_DECAY = [3, 7]
# need to be float
SELECT_TRUNCATION = [0.01, 0.1]
# ["ON", "OFF"]
SELECT_PASTEURIZATION = ["ON"]
# ["ON", "OFF"]
SELECT_NAN = ["OFF"]

